import { useState } from 'react';
import { Archive, Edit3, File, Inbox, Search, Send, Star } from 'lucide-react';
import ui from './PortalPage.module.css';
import styles from './Mail.module.css';

const messages=[
 {id:1,sender:'Dr. Sarah Jenkins',subject:'Your recent lab results',time:'10:42 AM',unread:true,snippet:'The CBC results are available. I have reviewed the report and added my notes.'},
 {id:2,sender:'Care Coordination',subject:'Appointment reminder',time:'Yesterday',unread:true,snippet:'A reminder for your upcoming consultation scheduled for October 15.'},
 {id:3,sender:'VitalHealth Support',subject:'Your health record was updated',time:'Oct 02',snippet:'A new document has been added securely to your personal health record.'},
];
export default function Mail(){const [active,setActive]=useState(1);const selected=messages.find(x=>x.id===active);return <div className={ui.page}><header className={ui.header}><div><div className={ui.eyebrow}>SECURE COMMUNICATIONS</div><h1>Messages</h1><p>Private conversations with your care team and hospital services.</p></div><button className={ui.primary}><Edit3 size={15}/>Compose message</button></header><div className={styles.mailLayout}><aside className={styles.folders}>{[{icon:Inbox,label:'Inbox',count:2},{icon:Star,label:'Starred'},{icon:Send,label:'Sent'},{icon:File,label:'Drafts',count:1},{icon:Archive,label:'Archive'}].map(({icon:Icon,label,count},i)=><button key={label} className={i===0?styles.active:''}><Icon size={15}/>{label}{count&&<span>{count}</span>}</button>)}</aside><section className={`${ui.card} ${styles.inbox}`}><div className={ui.cardHeader}><div><h2>Inbox</h2><p>3 recent conversations</p></div><div className={ui.search}><Search size={14}/><input placeholder="Search messages"/></div></div><div className={styles.columns}><div className={styles.messageList}>{messages.map(m=><button key={m.id} className={`${styles.message} ${m.id===active?styles.selected:''}`} onClick={()=>setActive(m.id)}><span className={ui.avatar}>{m.sender.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><span className={ui.listItemMain}>{m.unread&&<i/>}<strong>{m.sender}</strong><b>{m.subject}</b><p>{m.snippet}</p></span><time>{m.time}</time></button>)}</div><article className={styles.reader}><div className={styles.readerHeader}><span className={ui.avatar}>{selected.sender.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><h2>{selected.subject}</h2><p>From {selected.sender} · {selected.time}</p></div></div><div className={styles.readerBody}><p>Hello,</p><p>{selected.snippet}</p><p>You can reply directly if you have questions or need support before your next visit.</p><span>VitalHealth Care Team</span></div><div className={styles.reply}><input placeholder="Write a secure reply…"/><button className={ui.primary}>Send reply</button></div></article></div></section></div></div>}
