from .state import ClinicalSession

def generate_summary(session: ClinicalSession, document_data: dict = None) -> str:
    """
    Generates a structured, physician-ready Markdown summary of the clinical session.
    Incorporates conversational state and optionally structured OCR document data.
    """
    
    summary = f"# Clinical Intake Summary\n\n"
    summary += f"**Patient ID**: {session.patient_id}\n"
    summary += f"**Consultation Type**: {session.consultation_type.title()}\n"
    summary += f"**Chief Complaint**: {session.chief_complaint}\n\n"
    
    if session.red_flags:
        summary += "## 🚨 RED FLAGS\n"
        for flag in session.red_flags:
            summary += f"- {flag}\n"
        summary += "\n"
        
    summary += "## Structured History\n"
    for field, value in session.answered_fields.items():
        # Clean up field names for display
        display_field = field.replace('_', ' ').title()
        summary += f"**{display_field}**: {value}\n"
        
    if document_data:
        summary += "\n## Document Extraction (OCR)\n"
        
        meds = document_data.get("medications", [])
        if meds:
            summary += "### Medications\n"
            for med in meds:
                med_name = med.get("medicine", "Unknown")
                dose = med.get("dose", "")
                freq = med.get("frequency", "")
                summary += f"- {med_name} {dose} {freq}\n"
                
        labs = document_data.get("lab_results", [])
        if labs:
            summary += "### Lab Results\n"
            for lab in labs:
                test = lab.get("test", "Unknown")
                val = lab.get("value", "")
                unit = lab.get("unit", "")
                flag = lab.get("flag", "")
                summary += f"- {test}: {val} {unit} ({flag})\n"
                
    summary += "\n---\n*Generated by MediKiosk AI*"
    return summary
