import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, ChevronLeft, ChevronRight, Clock3, Download, FileImage, FileText, Filter, MapPin, MoreVertical, Paperclip, Plus, Printer, Search, Send, Settings, UserRound } from 'lucide-react';
import styles from './DoctorClinicalWorkspace.module.css';
import { useAuth } from '../../context/AuthContext';
import { fetchDoctorQueue, fetchPatientUnifiedHistory, fetchTeleconsultMessages, fetchTeleconsultSessions, getDoctorPatients, sendTeleconsultMessage } from '../../services/api';
const formatDate = (value) => value ? new Date(value).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';
const normalizeEntities = (value) => { if (!value) return {}; if (typeof value === 'object') return value; try { return JSON.parse(value); } catch { return {}; } };
const documentType = (value = '') => ({ lab_report: 'Lab Report', prescription: 'Prescription', scan: 'Imaging', medical_report: 'Medical Report', discharge_summary: 'Clinical Note' }[value] || value.replaceAll('_', ' ') || 'Document');

function PageHead({ eyebrow, title, copy, action, showQuote = true }) {
  return <header className={styles.pageHead}><div>{eyebrow && <span>{eyebrow}</span>}<h1>{title}</h1><p>{copy}</p></div>{showQuote && <blockquote>“Complete information<br/>leads to better care.”<i /></blockquote>}{action && <button><Plus />{action}</button>}</header>;
}
function PatientStrip({ patient, patients = [], onChange }) {
  if (!patient) return null;
  const initials = `${patient.firstName?.[0] || patient.patientName?.[0] || 'P'}${patient.lastName?.[0] || ''}`;
  return <section className={styles.patientStrip}><span className={styles.avatar}>{initials}</span><div><select value={patient.id} onChange={(e)=>onChange?.(e.target.value)}>{patients.map(p=><option value={p.id} key={p.id}>{p.patientName || `${p.firstName} ${p.lastName}`}</option>)}</select><small>{patient.age || '—'} years <b>•</b> {patient.gender || 'Not recorded'} <b>•</b> {patient.medicalId || '—'}</small></div><span className={styles.condition}>{patient.latestIntakeSummary ? 'Clinical history' : 'Active patient'}</span><div><small>Last Visit</small><strong>{patient.lastVisit || 'No visits recorded'}</strong></div><div><small>Access</small><strong>{patient.status || 'Granted'}</strong></div><button>View Patient Profile <ArrowRight /></button></section>;
}

export function DoctorRecords() {
  const { token } = useAuth();
  const [selected, setSelected] = useState(0);
  const [patients, setPatients] = useState([]);
  const [patientId, setPatientId] = useState('');
  const [history, setHistory] = useState(null);
  const [loading, setLoading] = useState(true);
  const [patientsLoading, setPatientsLoading] = useState(true);
  useEffect(()=>{ if(!token)return; setPatientsLoading(true);getDoctorPatients(token).then(res=>{const list=res?.patients||[];setPatients(list);setPatientId(list[0]?.id||'');}).catch(()=>setPatients([])).finally(()=>setPatientsLoading(false)); },[token]);
  useEffect(()=>{ if(!patientId||!token){setLoading(false);return;} setLoading(true);fetchPatientUnifiedHistory(patientId,token).then(res=>setHistory(res?.unifiedHistory||null)).catch(()=>setHistory(null)).finally(()=>setLoading(false)); },[patientId,token]);
  const records = useMemo(()=>(history?.documents||[]).map(d=>[d.file_name||'Untitled document',d.doc_summary||d.ai_summary||'Clinical document',documentType(d.document_type),formatDate(d.created_at),d.uploaded_by_name||'Patient',d]),[history]);
  useEffect(()=>setSelected(0),[patientId]);
  const current = records[selected];
  return <main className={`${styles.page} workspacePage`}><PageHead eyebrow="Home  ›  Records" title="Records" copy="Access and manage patient records, reports, scans and clinical documents."/>{patientsLoading?<section className={styles.noPatients}><UserRound/><div><strong>Loading connected patients…</strong><span>Preparing the clinical workspace.</span></div></section>:patients.length===0?<section className={styles.noPatients}><UserRound/><div><strong>No connected patients yet</strong><span>Connect a patient from the Patients page before opening their clinical records.</span></div><a href="/doctor/patients">Go to Patients <ArrowRight/></a></section>:<><PatientStrip patient={patients.find(p=>p.id===patientId)} patients={patients} onChange={setPatientId}/>
    <section className={styles.recordsGrid}><div className={styles.listPanel}><nav className={styles.tabs}>{['All Records','Lab Reports','Imaging','Prescriptions','Consultation Notes','Documents','Clinical Timeline'].map((x,i)=><button className={i===0?styles.active:''} key={x}>{x}</button>)}</nav><div className={styles.filters}><label><Search/><input placeholder="Search records..."/></label><button>All Types⌄</button><button>Latest First⌄</button><button><Filter/></button></div><div className={styles.tableHead}><span>Name</span><span>Type</span><span>Date</span><span>Uploaded By</span><span /></div>{records.map((r,i)=><button className={`${styles.recordRow} ${selected===i?styles.selected:''}`} onClick={()=>setSelected(i)} key={r[0]}><span className={`${styles.file} ${i%3===1?styles.purple:i%3===2?styles.blue:''}`}>{i%3===1?<FileImage/>:<FileText/>}</span><span><strong>{r[0]}</strong><small>{r[1]}</small></span><em>{r[2]}</em><span>{r[3]}</span><span>{r[4]}</span><MoreVertical/></button>)}</div>
      <aside className={styles.preview}>{loading?<div className={styles.emptyState}>Loading patient records…</div>:!current?<div className={styles.emptyState}>No clinical documents are available for this patient.</div>:<><header><div><span className={styles.file}><FileText/></span><div><h2>{current[0]}</h2><p>{current[3]} · {current[2]}</p></div></div><button>Open in New Tab</button></header><div className={styles.document}><div className={styles.docToolbar}>Clinical document preview</div><div className={styles.paper}><b>MediKiosk Clinic</b><small>Care Today. Healthier Tomorrows.</small><h3>{current[0]}</h3><p>{current[1]}</p><p className={styles.extractedText}>{current[5]?.extracted_text || 'No extracted text is available for this document. Open the original document to review its complete contents.'}</p></div></div><footer><h3>Record Details</h3><div><span><FileText/>{current[2]}</span><span><CalendarDays/>{current[3]}</span><span><UserRound/>{current[4]}</span></div></footer></>}</aside></section></>}</main>;
}

export function DoctorPrescriptions() {
  const { token, user } = useAuth();
  const [patients, setPatients] = useState([]);
  const [histories, setHistories] = useState([]);
  const [selected, setSelected] = useState(0);
  const [loading, setLoading] = useState(true);
  useEffect(()=>{ if(!token)return; setLoading(true);getDoctorPatients(token).then(async res=>{const list=res?.patients||[];setPatients(list);const loaded=await Promise.all(list.map(async patient=>{try{const data=await fetchPatientUnifiedHistory(patient.id,token);return {patient,history:data?.unifiedHistory||{}};}catch{return {patient,history:{}};}}));setHistories(loaded);}).catch(()=>{setPatients([]);setHistories([]);}).finally(()=>setLoading(false)); },[token]);
  const prescriptions = useMemo(()=>histories.flatMap(({patient,history})=>{
    const docs=(history.documents||[]).filter(d=>{const medications=normalizeEntities(d.extracted_entities).medications;return d.document_type==='prescription'||(Array.isArray(medications)&&medications.length>0);});
    const documentRows=docs.map(d=>{const entities=normalizeEntities(d.extracted_entities);const medications=Array.isArray(entities.medications)?entities.medications:[];return {date:formatDate(d.created_at),patient:patient.patientName||`${patient.firstName} ${patient.lastName}`,reason:entities.diagnosis||entities.condition||(d.document_type==='prescription'?'Prescription document':'Medication record'),medications,status:d.ocr_status==='failed'?'Needs review':'Sent',source:d};});
    const consultRows=(history.teleconsultSessions||[]).filter(s=>s.prescription).map(s=>({date:formatDate(s.created_at),patient:patient.patientName,reason:s.doctor_notes||'Teleconsultation',medications:String(s.prescription).split(/\n|,/).filter(Boolean).map(name=>({name:name.trim()})),status:s.status==='completed'?'Sent':'Draft',source:s}));
    return [...documentRows,...consultRows];
  }).sort((a,b)=>new Date(b.source.created_at)-new Date(a.source.created_at)),[histories]);
  const current=prescriptions[selected];
  const currentPatient=patients.find(p=>p.patientName===current?.patient);
  return <main className={`${styles.page} workspacePage`}><PageHead eyebrow="Prescriptions" title="Prescriptions" copy="Create, view and manage prescriptions. Send them to patients and pharmacies securely." action="New Prescription" showQuote={false}/>
    <nav className={styles.tabs}>{['All Prescriptions','Drafts','Recent','Templates','Medicine Database'].map((x,i)=><button className={i===0?styles.active:''} key={x}>{x}</button>)}</nav><div className={styles.filters}><label><Search/><input placeholder="Search by patient name, prescription ID or medicine..."/></label><button>Date Range⌄</button><button>Patient⌄</button><button>Status⌄</button><button>Consultation Type⌄</button></div>
    <section className={styles.prescriptionGrid}><div className={styles.prescriptionList}><div className={`${styles.rxRow} ${styles.rxHead}`}>{['Date','Patient','Diagnosis / Reason','Medicines','Status','Actions'].map(x=><span key={x}>{x}</span>)}</div>{loading?<div className={styles.emptyState}>Loading prescriptions…</div>:prescriptions.length===0?<div className={styles.emptyState}>No prescriptions are available across your connected patients.</div>:prescriptions.map((r,i)=><button className={`${styles.rxRow} ${selected===i?styles.selectedRx:''}`} onClick={()=>setSelected(i)} key={`${r.patient}-${r.date}-${i}`}><span>{r.date}</span><span>{r.patient}</span><span>{r.reason}</span><span>{r.medications.length} medicine{r.medications.length===1?'':'s'}</span><em className={r.status==='Draft'?styles.draft:''}>{r.status}</em><MoreVertical/></button>)}</div><aside className={styles.rxPreview}>{!current?<div className={styles.emptyState}>Select a prescription to review its clinical details.</div>:<><header><div><strong>Prescription #{String(current.source.id||'clinical').slice(0,12).toUpperCase()}</strong><small>{current.date}</small></div><em>{current.status}</em><MoreVertical/></header><div className={styles.rxPatient}><span className={styles.avatar}>{current.patient.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><strong>{current.patient}</strong><small>{currentPatient?.age||'—'} years · {currentPatient?.gender||'Not recorded'} · {currentPatient?.medicalId||'—'}</small></div><button>View Patient</button></div><nav><b>Prescription</b><span>Consultation Summary</span><span>Notes</span></nav><article><div className={styles.doctorSign}><b>℞</b><span><strong>Dr. {user?.firstName||''} {user?.lastName||''}</strong><small>{user?.specialization||'Medical Specialist'} · MediKiosk Clinic</small></span></div><h4>Diagnosis / Reason</h4><p>{current.reason}</p><table><tbody>{current.medications.length?current.medications.map((med,i)=><tr key={i}><td>{med.name||med.medicine||String(med)}</td><td>{med.dosage||med.dose||'—'}</td><td>{med.frequency||'As directed'}</td></tr>):<tr><td>Prescription details are available in the original clinical document.</td></tr>}</tbody></table></article><footer><button><Printer/>Print</button><button><Download/>Download PDF</button><button><Send/>Send to Patient</button></footer></>}</aside></section></main>;
}

export function DoctorMessages() {
  const { token } = useAuth();
  const [sessions,setSessions]=useState([]);
  const [active,setActive]=useState(0);
  const [messages,setMessages]=useState([]);
  const [draft,setDraft]=useState('');
  const [loading,setLoading]=useState(true);
  useEffect(()=>{if(!token)return;setLoading(true);fetchTeleconsultSessions(token).then(res=>setSessions(res?.sessions||[])).catch(()=>setSessions([])).finally(()=>setLoading(false));},[token]);
  const session=sessions[active];
  useEffect(()=>{if(!session?.id||!token){setMessages([]);return;}fetchTeleconsultMessages(session.id,token).then(res=>setMessages(res?.messages||[])).catch(()=>setMessages([]));},[session?.id,token]);
  const sendMessage=async()=>{const value=draft.trim();if(!value||!session?.id)return;try{await sendTeleconsultMessage(session.id,value,'text',token);setDraft('');const res=await fetchTeleconsultMessages(session.id,token);setMessages(res?.messages||[]);}catch{/* preserve draft when sending fails */}};
  const patient=session?.patient;
  const initials=patient?.name?.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()||'P';
  return <main className={`${styles.page} workspacePage`}><PageHead title="Messages" copy="Communicate securely with your patients. Share updates, respond to queries, and follow up on care." action="New Message" showQuote={false}/>
    {loading?<section className={styles.noPatients}><UserRound/><div><strong>Loading conversations…</strong><span>Retrieving secure consultation threads.</span></div></section>:!session?<section className={styles.noPatients}><UserRound/><div><strong>No patient conversations yet</strong><span>Messages will appear after a teleconsultation session is created.</span></div></section>:<section className={styles.messages}><aside className={styles.conversations}><label><Search/><input placeholder="Search conversations..."/></label><nav><button>All</button><button>Unread</button><button>Patients</button></nav>{sessions.map((s,i)=>{const name=s.patient?.name||'Patient';const init=name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase();return <button className={active===i?styles.selectedConversation:''} onClick={()=>setActive(i)} key={s.id}><span className={styles.avatar}>{init}</span><span><strong>{name}</strong><small>{s.reason||s.patientNotes||'Consultation thread'}</small></span><time>{s.unreadCount?`${s.unreadCount} new`:formatDate(s.createdAt)}</time></button>;})}</aside>
      <section className={styles.chat}><header><span className={styles.avatar}>{initials}</span><div><strong>{patient?.name||'Patient'}</strong><small>{patient?.gender||'Not recorded'} · {session.reason||'Consultation'}</small></div><button>View Patient</button><MoreVertical/></header><div className={styles.thread}><time>{formatDate(session.createdAt)}</time>{messages.length?messages.map(message=><p className={message.isMe?styles.outgoing:''} key={message.id}>{message.message}</p>):<div className={styles.emptyState}>No messages in this consultation yet.</div>}</div><footer><Paperclip/><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendMessage()} placeholder="Type a message..."/><button onClick={sendMessage}><Send/></button></footer></section>
      <aside className={styles.patientDetails}><h3>Patient Details</h3><div><span className={styles.avatar}>{initials}</span><strong>{patient?.name||'Patient'}</strong><small>{patient?.email||patient?.phone||'Contact not recorded'}<br/>{patient?.gender||'Not recorded'}</small></div><button>View Profile</button><hr/><small>Consultation reason</small><strong>{session.reason||'Not specified'}</strong><small>Session status</small><strong>{session.status?.replaceAll('_',' ')||'—'}</strong><small>Scheduled</small><strong>{formatDate(session.scheduledAt||session.requestedTime)}</strong><hr/><h3>Quick Actions</h3>{['Schedule Appointment','Share Document','Create Prescription','Add Note'].map(x=><button className={styles.detailAction} key={x}><ChevronRight/>{x}</button>)}</aside>
    </section>}</main>;
}

export function DoctorSchedule() {
  const { token }=useAuth();
  const [queue,setQueue]=useState([]);
  const [selected,setSelected]=useState(0);
  const [loading,setLoading]=useState(true);
  useEffect(()=>{if(!token)return;setLoading(true);fetchDoctorQueue(token).then(res=>setQueue(res?.queue||[])).catch(()=>setQueue([])).finally(()=>setLoading(false));},[token]);
  const slots=useMemo(()=>queue.map(item=>{const patient=item.patient||{};const name=item.name||`${patient.firstName||item.patient_first_name||''} ${patient.lastName||item.patient_last_name||''}`.trim()||'Patient';const raw=item.scheduledAt||item.scheduled_at;const date=raw?new Date(raw):null;const status=item.appointmentStatus||item.status||'scheduled';return {id:item.appointmentId||item.id,name,patient,date,reason:item.reason||item.intake?.chiefComplaint||'Consultation',type:item.appointmentType||item.appointment_type||'Consultation',status,tone:status==='checked_in'?'green':status==='in_consultation'?'orange':status==='cancelled'?'break':'blue'};}),[queue]);
  const active=slots[selected];
  const calendarDate=active?.date||new Date();
  const daysInMonth=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,0).getDate();
  const monthLabel=calendarDate.toLocaleDateString('en',{month:'long',year:'numeric'});
  const dayLabel=calendarDate.toLocaleDateString('en',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
  return <main className={`${styles.page} workspacePage`}><header className={styles.scheduleHead}><div><span>Appointments</span><h1>Manage Your Schedule</h1><p>View, schedule and manage appointments. Stay on top of your day.</p></div><button><Settings/>Availability Settings</button><button><Plus/>New Appointment</button></header><section className={styles.scheduleGrid}>
    <aside className={styles.calendarPane}><header><strong>{monthLabel}</strong><span><ChevronLeft/><ChevronRight/></span></header><div className={styles.miniCalendar}>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=><b key={x}>{x}</b>)}{Array.from({length:daysInMonth},(_,i)=><span className={i+1===calendarDate.getDate()?styles.today:''} key={i}>{i+1}</span>)}</div><hr/><h3>Filters</h3><b>Appointment Type</b>{['Consultation','Follow-up','Procedure','Teleconsultation'].map(x=><label key={x}><input type="checkbox"/>{x}</label>)}<b>Status</b>{['Scheduled','Checked In','In Consultation','Completed','Cancelled'].map(x=><label key={x}><i/>{x}</label>)}</aside>
    <section className={styles.dayPane}><header><button><ChevronLeft/></button><h2>{dayLabel}</h2><nav><button>Day</button><button>Week</button><button>Month</button></nav><button>Today</button></header><div className={styles.slotList}>{loading?<div className={styles.emptyState}>Loading schedule…</div>:slots.length===0?<div className={styles.emptyState}>No appointments are currently scheduled.</div>:slots.map((s,i)=><article className={styles[s.tone]} onClick={()=>setSelected(i)} key={s.id||i}><time>{s.date?s.date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'TBD'}</time><div><strong>{s.name}</strong><small>{s.type} · {s.reason}</small></div><em>{s.status.replaceAll('_',' ')}</em><MoreVertical/></article>)}</div></section>
    <aside className={styles.appointmentDetail}>{!active?<div className={styles.emptyState}>Select an appointment to view details.</div>:<><header><span className={styles.avatar}>{active.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</span><div><h3>{active.name}</h3><small>{active.patient.gender||'Not recorded'}<br/>PID: {String(active.patient.id||'—').slice(0,8)}</small></div><button>View Profile</button></header><nav><b>Appointment</b><span>Patient History</span></nav><article><header><h3>Appointment Details</h3><button>Edit</button></header><p><CalendarDays/>{formatDate(active.date)}</p><p><Clock3/>{active.date?active.date.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'Time not set'}</p><p><MapPin/>{active.patient.location||'Clinic'}</p><p><FileText/>{active.type}</p><p>{active.reason}</p></article><h3>Quick Actions</h3><div className={styles.scheduleActions}>{['Check In','Reschedule','Cancel','Add Note'].map(x=><button key={x}>{x}</button>)}</div></> }</aside>
  </section></main>;
}
