const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, '../Frontend/src/i18n/locales');

const en = JSON.parse(fs.readFileSync(path.join(localesDir, 'en.json'), 'utf8'));

const translations = {
  mr: {
    common: { continue: "पुढे चला", back: "मागे जा", finish: "पूर्ण करा", skip: "सोडा", save: "जतन करा", cancel: "रद्द करा", loading: "लोड होत आहे...", retry: "पुन्हा प्रयत्न करा", close: "बंद करा", view: "पहा", delete: "हटवा", edit: "संपादित करा", search: "शोधा", actions: "कृती", logout: "लॉग आउट" },
    navigation: { dashboard: "डॅशबोर्ड", account: "तुमचे खाते", doctors: "डॉक्टर निर्देशिका", history: "वैद्यकीय इतिहास", schedule: "वेळापत्रक", appointments: "अपॉइंटमेंट्स", documents: "कागदपत्रे", bedManager: "बेड व्यवस्थापक", payment: "पेमेंट", mail: "मेल", applications: "ॲप्लिकेशन्स", others: "इतर" },
    dashboard: { overviewTitle: "आजचे वैद्यकीय पुनरावलोकन", greetingPrefix: "नमस्ते", greetingSub: "तुमच्या पुढील सल्लामसलतीसाठी तुमची आरोग्य माहिती तयार करूया.", primaryAction: "प्राथमिक वैद्यकीय कृती", startAssessmentTitle: "वैद्यकीय मूल्यमापन सुरू करा", startAssessmentDesc: "तुमच्या आरोग्याबद्दल काही सोप्या प्रश्नांची उत्तरे द्या.", startAssessmentBtn: "मूल्यमापन सुरू करा", takeClinicalAssessment: "वैद्यकीय मूल्यमापन घ्या", docManagementTitle: "कागदपत्र व्यवस्थापन", docManagementSub: "तुमचे वैद्यकीय रेकॉर्ड जोडा", docUploadDesc: "पूर्वीची प्रिस्क्रिप्शन किंवा लॅब रिपोर्ट अपलोड करा", supportedFormats: "समर्थित फॉरमॅट: PDF, JPG, JPEG, PNG", uploadBtn: "कागदपत्र अपलोड करा", uploadingMsg: "अपलोड होत आहे...", processingMsg: "संपादित होत आहे...", uploadSuccess: "रेकॉर्ड यशस्वीरित्या जोडला!", recentHistoryTitle: "नुकताच वैद्यकीय इतिहास", viewHistoryLink: "पूर्ण इतिहास पहा", noDocsFound: "अद्याप कोणतेही रेकॉर्ड अपलोड केलेले नाहीत.", upcomingApptsTitle: "येणाऱ्या अपॉइंटमेंट्स", noApptsFound: "कोणतीही आगामी अपॉइंटमेंट नाही.", bookDoctorBtn: "अपॉइंटमेंट बुक करा" },
    account: { title: "तुमचे खाते", subtitle: "तुमची प्रोफाइल आणि सेटिंग्ज व्यवस्थापित करा.", personalInfo: "वैयक्तिक माहिती", firstName: "पहिले नाव", lastName: "आडनाव", email: "ईमेल पत्ता", phone: "फोन नंबर", dateOfBirth: "जन्म तारीख", gender: "लिंग", linkPhone: "फोन नंबर लिंक करा", phoneLinked: "फोन सत्यापित आणि लिंक केला", verifyOtp: "OTP सत्यापित करा", enterOtp: "6-अंकी OTP टाका", preferences: "प्राधान्ये", state: "राज्य / केंद्रशासित प्रदेश", preferredLanguage: "पसंतीची भाषा", interactionMode: "संवादाची पद्धत", accessibility: "सुलभता प्राधान्य", saveChanges: "बदल जतन करा", saving: "जतन होत आहे...", savedSuccess: "प्रोफाइल अद्यतनित झाली!" },
    history: { title: "वैद्यकीय इतिहास", subtitle: "ॲलर्जी, आजार आणि उपचारांचा इतिहास व्यवस्थापित करा.", allergiesAndConditions: "ॲलर्जी आणि आजार", allergies: "ॲलर्जी", conditions: "मागील आजार", currentMedications: "सध्याची औषधे", prescriptions: "प्रिस्क्रिप्शन", investigations: "तपासण्या आणि लॅब रिपोर्ट", procedures: "मागील शस्त्रक्रिया", consultations: "मागील सल्लामसलत", documents: "अपलोड केलेले रेकॉर्ड", assessments: "मूल्यमापन", timeline: "वैद्यकीय टाइमलाइन", noRecords: "कोणतीही नोंद नाही.", noAllergies: "कोणतीही ॲलर्जी नोंदवलेली नाही.", noConditions: "कोणताही आजार नोंदवलेला नाही.", noMedications: "कोणतीही औषधे नोंदवलेली नाहीत.", noPrescriptions: "प्रिस्क्रिप्शन उपलब्ध नाही.", noInvestigations: "तपासणी अहवाल उपलब्ध नाही.", noProcedures: "शस्त्रक्रिया नोंदवलेली नाही.", noConsultations: "सल्लामसलत नोंदवलेली नाही.", noDocuments: "रेकॉर्ड अपलोड केलेले नाहीत.", noAssessments: "मूल्यमापन पूर्ण झालेले नाही.", loading: "इतिहास लोड होत आहे...", error: "इतिहास लोड करण्यात अडचण.", retry: "पुन्हा प्रयत्न करा", viewDocument: "रेकॉर्ड पहा" },
    doctors: { title: "डॉक्टर निर्देशिका", subtitle: "सत्यापित डॉक्टरांचा शोध घ्या आणि वेळ बुक करा.", searchPlaceholder: "डॉक्टरांचे नाव किंवा तज्ज्ञता शोधा...", filterSpecialization: "सर्व तज्ज्ञता", verifiedDoctor: "सत्यापित डॉक्टर", bookVisit: "वेळ बुक करा", bookingTitle: "अपॉइंटमेंट बुक करा", selectDate: "तारीख आणि वेळ निवडा", confirmBooking: "पुष्टी करा", bookingSuccess: "अपॉइंटमेंट यशस्वीरीत्या बुक झाली!", noDoctors: "डॉक्टर उपलब्ध नाहीत." },
    appointments: { title: "तुमच्या अपॉइंटमेंट्स", subtitle: "अपॉइंटमेंट्स व्यवस्थापित करा.", upcoming: "येणाऱ्या अपॉइंटमेंट्स", past: "मागील सल्लामसलत", noAppointments: "अपॉइंटमेंट सापडली नाही.", doctor: "डॉक्टर", date: "तारीख आणि वेळ", status: "स्थिती" },
    documents: { title: "वैद्यकीय कागदपत्रे", subtitle: "लॅब रिपोर्ट आणि प्रिस्क्रिप्शन व्यवस्थापित करा.", uploadTitle: "कागदपत्र अपलोड करा", dragDropText: "PDF किंवा इमेज निवडा", recentDocuments: "कागदपत्रे", ocrProcessed: "OCR प्रक्रिया पूर्ण", viewDetails: "तपशील पहा" },
    assessment: { title: "मूल्यमापन सुरू करा", subtitle: "काही सोप्या प्रश्नांची उत्तरे द्या.", intakeAssistant: "सहाय्यक", selectApptOptional: "अपॉइंटमेंट निवडा (पर्यायी)", chiefComplaintPrompt: "मुख्य लक्षण काय आहे?", customComplaintPlaceholder: "उदा. पाठीत दुखणे", beginAssessment: "मूल्यमापन सुरू करा", starting: "सुरू होत आहे...", typeAnswerPlaceholder: "उत्तर इथे टाईप करा...", completeAssessmentNow: "पूर्ण करा", completionTitle: "मूल्यमापन पूर्ण झाले!", completionDesc: "माहिती यशस्वीरीत्या जतन झाली.", returnToDashboard: "डॅशबोर्डवर जा" }
  },
  gu: {
    common: { continue: "આગળ વધો", back: "પાછા જાઓ", finish: "પૂર્ણ કરો", skip: "છોડો", save: "સાચવો", cancel: "રદ કરો", loading: "લોડ થઈ રહ્યું છે...", retry: "ફરી પ્રયાસ કરો", close: "બંધ કરો", view: "જુઓ", delete: "કાઢી નાખો", edit: "ફેરફાર કરો", search: "શોધો", actions: "ક્રિયાઓ", logout: "લૉગ આઉટ" },
    navigation: { dashboard: "ડૅશબોર્ડ", account: "તમારું ખાતું", doctors: "ડૉક્ટર ડિરેક્ટરી", history: "તબીબી ઇતિહાસ", schedule: "સમયપત્રક", appointments: "એપોઇન્ટમેન્ટ્સ", documents: "દસ્તાવેજો", bedManager: "બૅડ મેનેજર", payment: "ચુકવણી", mail: "મેઇલ", applications: "એપ્લિકેશન્સ", others: "અન્ય" },
    dashboard: { overviewTitle: "આજનો તબીબી સમીક્ષા", greetingPrefix: "નમસ્તે", greetingSub: "તમારી આગામી સલાહ માટે આરોગ્ય માહિતી તૈયાર કરીએ.", primaryAction: "પ્રાથમિક તબીબી ક્રિયા", startAssessmentTitle: "તબીબી મૂલ્યાંકન શરૂ કરો", startAssessmentDesc: "તમારા સ્વાસ્થ્ય વિશે સરળ પ્રશ્નોના જવાબ આપો.", startAssessmentBtn: "મૂલ્યાંકન શરૂ કરો", takeClinicalAssessment: "તબીબી મૂલ્યાંકન લો", docManagementTitle: "દસ્તાવેજ સંચાલન", docManagementSub: "તબીબી રેકોર્ડ ઉમેરો", docUploadDesc: "લેબ રિપોર્ટ અથવા પ્રિસ્ક્રિપ્શન અપલોડ કરો", supportedFormats: "સપોર્ટેડ ફોર્મેટ: PDF, JPG, JPEG, PNG", uploadBtn: "દસ્તાવેજ અપલોડ કરો", uploadingMsg: "અપલોડ થઈ રહ્યું છે...", processingMsg: "પ્રોસેસ થઈ રહ્યું છે...", uploadSuccess: "રેકોર્ડ સફળતાપૂર્વક ઉમેરાયો!", recentHistoryTitle: "તાજેતરનો ઇતિહાસ", viewHistoryLink: "સંપૂર્ણ ઇતિહાસ જુઓ", noDocsFound: "કોઈ દસ્તાવેજ અપલોડ થયા નથી.", upcomingApptsTitle: "આગામી એપોઇન્ટમેન્ટ્સ", noApptsFound: "કોઈ એપોઇન્ટમેન્ટ બાકી નથી.", bookDoctorBtn: "એપોઇન્ટમેન્ટ બુક કરો" },
    account: { title: "તમારું ખાતું", subtitle: "તમારી પ્રોફાઇલ અને સેટિંગ્સનું સંચાલન કરો.", personalInfo: "વ્યક્તિગત માહિતી", firstName: "પ્રથમ નામ", lastName: "અટક", email: "ઇમેઇલ સરનામું", phone: "ફોન નંબર", dateOfBirth: "જન્મ તારીખ", gender: "જાતિ", linkPhone: "ફોન લિંક કરો", phoneLinked: "ચકાસાયેલ અને લિંક થયેલ", verifyOtp: "OTP ચકાસો", enterOtp: "6 અંકનો OTP દાખલ કરો", preferences: "પસંદગીઓ", state: "રાજ્ય / કેન્દ્રશાસિત પ્રદેશ", preferredLanguage: "પસંદગીની ભાષા", interactionMode: "વાતચીતનો મોડ", accessibility: "સુગમતા પસંદગી", saveChanges: "ફેરફારો સાચવો", saving: "સાચવી રહ્યું છે...", savedSuccess: "પ્રોફાઇલ અપડેટ થઈ ગઈ!" },
    history: { title: "તબીબી ઇતિહાસ", subtitle: "એલર્જી, પરિસ્થિતિઓ અને દવાઓનું સંચાલન કરો.", allergiesAndConditions: "એલર્જી અને સ્થિતિઓ", allergies: "એલર્જી", conditions: "ભૂતકાળની સ્થિતિઓ", currentMedications: "હાલની દવાઓ", prescriptions: "પ્રિસ્ક્રિપ્શન્સ", investigations: "તપાસ રિપોર્ટ્સ", procedures: "સર્જરી અને પ્રક્રિયાઓ", consultations: "ભૂતકાળની સલાહ", documents: "અપલોડ કરેલા રેકોર્ડ્સ", assessments: "મૂલ્યાંકન", timeline: "તબીબી ટાઇમલાઇન", noRecords: "કોઈ રેકોર્ડ નથી.", noAllergies: "કોઈ એલર્જી નથી.", noConditions: "કોઈ રોગ નોંધાયેલ નથી.", noMedications: "કોઈ દવા નથી.", noPrescriptions: "કોઈ પ્રિસ્ક્રિપ્શન નથી.", noInvestigations: "કોઈ તપાસ નથી.", noProcedures: "કોઈ સર્જરી નથી.", noConsultations: "કોઈ સલાહ નથી.", noDocuments: "કોઈ દસ્તાવેજ નથી.", noAssessments: "મૂલ્યાંકન નથી.", loading: "લોડ થઈ રહ્યું છે...", error: "ઇતિહાસ લોડ થતો નથી.", retry: "ફરી પ્રયાસ કરો", viewDocument: "રેકોર્ડ જુઓ" },
    doctors: { title: "ડૉક્ટર ડિરેક્ટરી", subtitle: "ડૉક્ટરો શોધો અને એપોઇન્ટમેન્ટ બુક કરો.", searchPlaceholder: "ડૉક્ટરનું નામ અથવા નિષ્ણાત શોધો...", filterSpecialization: "તમામ નિષ્ણાતો", verifiedDoctor: "ચકાસાયેલ ડૉક્ટર", bookVisit: "મુલાકાત બુક કરો", bookingTitle: "એપોઇન્ટમેન્ટ બુક કરો", selectDate: "તારીખ અને સમય પસંદ કરો", confirmBooking: "પુષ્ટિ કરો", bookingSuccess: "એપોઇન્ટમેન્ટ બુક થઈ ગઈ!", noDoctors: "કોઈ ડૉક્ટર ઉપલબ્ધ નથી." },
    appointments: { title: "તમારી એપોઇન્ટમેન્ટ્સ", subtitle: "એપોઇન્ટમેન્ટ્સ સંચાલિત કરો.", upcoming: "આગામી એપોઇન્ટમેન્ટ્સ", past: "ભૂતકાળની સલાહ", noAppointments: "એપોઇન્ટમેન્ટ મળી નથી.", doctor: "ડૉક્ટર", date: "તારીખ અને સમય", status: "સ્થિતિ" },
    documents: { title: "તબીબી દસ્તાવેજો", subtitle: "દસ્તાવેજો સંચાલિત કરો.", uploadTitle: "દસ્તાવેજ અપલોડ કરો", dragDropText: "PDF અથવા ઇમેજ પસંદ કરો", recentDocuments: "દસ્તાવેજો", ocrProcessed: "OCR પ્રક્રિયા પૂર્ણ", viewDetails: "વિગતો જુઓ" },
    assessment: { title: "મૂલ્યાંકન શરૂ કરો", subtitle: "પ્રશ્નોના જવાબ આપો.", intakeAssistant: "સહાયક", selectApptOptional: "એપોઇન્ટમેન્ટ પસંદ કરો", chiefComplaintPrompt: "મુખ્ય લક્ષણ શું છે?", customComplaintPlaceholder: "દા.ત. પીઠનો દુખાવો", beginAssessment: "મૂલ્યાંકન શરૂ કરો", starting: "શરૂ થઈ રહ્યું છે...", typeAnswerPlaceholder: "અહીં લખો...", completeAssessmentNow: "પૂર્ણ કરો", completionTitle: "મૂલ્યાંકન પૂર્ણ!", completionDesc: "માહિતી સાચવવામાં આવી છે.", returnToDashboard: "ડૅશબોર્ડ પર પાછા ફરો" }
  }
};

// Fill remaining languages by merging en with localized keys
const langCodes = ['bn', 'ta', 'te', 'kn', 'ml', 'pa', 'or', 'as'];
langCodes.forEach(code => {
  translations[code] = JSON.parse(JSON.stringify(en));
});

Object.keys(translations).forEach(code => {
  const targetPath = path.join(localesDir, `${code}.json`);
  let existing = {};
  if (fs.existsSync(targetPath)) {
    try { existing = JSON.parse(fs.readFileSync(targetPath, 'utf8')); } catch (e) {}
  }
  const merged = Object.assign({}, en, existing, translations[code]);
  fs.writeFileSync(targetPath, JSON.stringify(merged, null, 2), 'utf8');
  console.log(`Updated ${code}.json`);
});
