/**
 * Utilities for cleaning and structuring raw clinical intake summaries,
 * doctor consultation notes, and AI synthesis narratives for display
 * in the Medical Passport web UI and PDF documents.
 */

export function cleanSummaryText(str) {
  if (!str) return "";
  return String(str)
    .normalize("NFKC")
    .replace(/[\u2018\u2019\u0060\u00B4]/g, "'")
    .replace(/[\u201C\u201D\u00AB\u00BB]/g, '"')
    .replace(/[\u2013\u2014\u2015\u2212]/g, "-")
    .replace(/[\u00A0\u1680\u180E\u2000-\u200B\u202F\u205F\u3000\uFEFF]/g, " ")
    .replace(/```[\s\S]*?```/g, "")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/__([^_]+)__/g, "$1")
    .replace(/_([^_]+)_/g, "$1")
    .replace(/~~([^~]+)~~/g, "$1")
    .replace(/^[#]+\s*/, "")
    .replace(/[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]/gu, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Parses raw summary string (multi-line or inline markdown) and optional recent assessment
 * into a structured clinical snapshot.
 */
export function parseClinicalSummary(rawSummary, recentAssessment = null) {
  const result = {
    presentationList: [],
    presentationMap: {},
    overview: "",
    clinicalFlags: [],
    provenanceDate: null,
    source: "MediKiosk Clinical Intake",
    isAiGenerated: true,
    hasContent: false
  };

  const raw = typeof rawSummary === "string" ? rawSummary : "";

  // 1. Strictly sanitize database IDs & UUIDs
  let clean = raw
    .replace(/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/gi, "")
    .replace(/(?:\*\*|\b)(?:Patient|Session|User)\s*ID(?:\*\*|\b)\s*:\s*[^\r\n*]*/gi, "")
    .replace(/(?:---|===|\*\*\*)\s*\*?Generated by [^*]*\*?/gi, "")
    .replace(/\*?Generated by MediKiosk AI\*?/gi, "");

  const pMap = new Map();
  const matchedTokens = [];

  // 2. Extract inline markdown **Key**: Value
  const inlineRegex = /\*\*([A-Za-z\s]{2,30})\*\*\s*:\s*([^*#\r\n]+?)(?=(?:\*\*[A-Za-z\s]{2,30}\*\*|##|#|---|===|\r?\n|$))/gi;
  let match;
  while ((match = inlineRegex.exec(clean)) !== null) {
    const key = match[1].trim();
    let val = match[2].trim().replace(/^[:\-\s]+|[:\-\s]+$/g, "");
    if (val && !/^(?:none|n\/a|null|nil|undefined)$/i.test(val)) {
      if (/red flag|clinical flag|triage/i.test(key)) {
        val.split(/[,;•|]/).forEach(f => {
          const tf = f.trim();
          if (tf && !/^(?:none|no|nil|neg|negative|n\/a)$/i.test(tf)) result.clinicalFlags.push(tf);
        });
      } else if (!/language|patient\s*id|session\s*id|user\s*id/i.test(key)) {
        pMap.set(key, val);
      }
      matchedTokens.push(match[0]);
    }
  }

  // Remove matched inline tokens to process remaining text
  let remaining = clean;
  matchedTokens.forEach(token => {
    remaining = remaining.replace(token, " ");
  });

  const lines = remaining.split(/\r?\n/);
  const narrativeLines = [];

  for (let l of lines) {
    let line = l.trim();
    if (!line) continue;

    // Filter structural noise
    if (/^(?:#+|-{3,}|={3,}|\*|\+)\s*$/i.test(line)) continue;
    if (/^#+\s*(?:Clinical Intake Summary|Structured History|Assessment|Intake|Narrative)/i.test(line)) continue;
    if (/^language[:\s]+/i.test(line)) continue;

    // Line-based Key: Value
    const kvMatch = line.match(/^([A-Za-z\s]{2,30})[:=]\s*(.+)$/);
    if (kvMatch) {
      const key = kvMatch[1].trim();
      let val = kvMatch[2].replace(/^[#\*\-_\s]+|[#\*\-_\s]+$/g, "").trim();
      if (val && !/^(?:none|n\/a|null|nil|undefined)$/i.test(val)) {
        if (/red flag|clinical flag|triage/i.test(key)) {
          val.split(/[,;•|]/).forEach(f => {
            const tf = f.trim();
            if (tf && !/^(?:none|no|nil|neg|negative|n\/a)$/i.test(tf)) result.clinicalFlags.push(tf);
          });
          continue;
        } else if (!/language|patient\s*id|session\s*id|user\s*id/i.test(key)) {
          pMap.set(key, val);
          continue;
        }
      }
    }

    // Clean markdown remnants
    const cleanLine = line
      .replace(/^[#]+\s*/, "")
      .replace(/\*\*([^*]+)\*\*/g, "$1")
      .replace(/\*([^*]+)\*/g, "$1")
      .replace(/^[-•*]\s*/, "")
      .trim();

    if (cleanLine.length > 2 && !/^(?:Clinical Intake Summary|Structured History|Assessment|Intake|Narrative)$/i.test(cleanLine)) {
      narrativeLines.push(cleanLine);
    }
  }

  // Supplement with recentAssessment if available
  if (recentAssessment) {
    if (recentAssessment.chiefComplaint && !pMap.has("Chief Complaint") && !/^(?:general\s*intake|general\s*clinical\s*intake)$/i.test(recentAssessment.chiefComplaint)) {
      pMap.set("Chief Complaint", recentAssessment.chiefComplaint);
    }
    if (recentAssessment.consultationType && !pMap.has("Consultation Type")) {
      pMap.set("Consultation Type", recentAssessment.consultationType);
    }
    if (recentAssessment.date) {
      result.provenanceDate = recentAssessment.date;
    }
    if (recentAssessment.source) {
      result.source = recentAssessment.source;
    }
  }

  // Canonical presentation key ordering
  const canonicalOrder = [
    "Chief Complaint",
    "Consultation Type",
    "Onset",
    "Duration",
    "Severity",
    "Associated Symptoms",
    "Assessment Date"
  ];

  canonicalOrder.forEach(k => {
    for (let [mapKey, val] of pMap.entries()) {
      if (mapKey.toLowerCase() === k.toLowerCase()) {
        result.presentationList.push({
          key: k,
          label: k,
          value: val,
          isPrimary: k === "Chief Complaint"
        });
        result.presentationMap[k] = val;
        pMap.delete(mapKey);
        break;
      }
    }
  });

  for (let [k, val] of pMap.entries()) {
    result.presentationList.push({
      key: k,
      label: k,
      value: val,
      isPrimary: false
    });
    result.presentationMap[k] = val;
  }

  result.overview = narrativeLines.join(" ").replace(/\s+/g, " ").trim();
  if (!result.overview && result.presentationList.length > 0) {
    const cc = result.presentationMap["Chief Complaint"];
    const cType = result.presentationMap["Consultation Type"] ? `${result.presentationMap["Consultation Type"]} consultation` : "clinical intake";
    const onset = result.presentationMap["Onset"];
    const duration = result.presentationMap["Duration"];
    const severity = result.presentationMap["Severity"];
    const symptoms = result.presentationMap["Associated Symptoms"];

    const sentences = [];
    if (cc) {
      sentences.push(`Patient completed an ${cType.toLowerCase()} presenting with ${cc}.`);
    } else {
      sentences.push(`Patient completed an ${cType.toLowerCase()} assessment.`);
    }

    const details = [];
    if (onset) details.push(`onset recorded as ${onset.toLowerCase()}`);
    if (duration) details.push(`duration of ${duration.toLowerCase()}`);
    if (severity) details.push(`severity evaluated as ${severity.toLowerCase()}`);
    if (details.length > 0) {
      sentences.push(`Clinical presentation indicates ${details.join(", ")}.`);
    }

    if (symptoms && (!cc || symptoms.toLowerCase() !== cc.toLowerCase())) {
      sentences.push(`Associated symptoms noted during intake: ${symptoms}.`);
    }

    result.overview = sentences.join(" ");
  }

  if (!result.overview && result.presentationList.length === 0 && clean.trim()) {
    result.overview = clean.trim();
  }

  result.hasContent = result.presentationList.length > 0 || result.clinicalFlags.length > 0 || !!result.overview;

  return result;
}
