import jsPDF from "jspdf";

/**
 * Generates and downloads a beautifully formatted, official MediKiosk Clinical AI Assessment PDF Report
 */
export async function downloadSummaryPDF({
  title = "Clinical AI Intake Assessment Report",
  patientName = "Patient",
  chiefComplaint = "",
  date = new Date().toLocaleDateString(),
  answeredFields = {},
  redFlags = [],
  summaryText = "",
}) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  const primaryColor = [13, 148, 136]; // #0d9488 Teal
  const darkTextColor = [30, 41, 59]; // #1e293b
  const grayColor = [100, 116, 139]; // #64748b

  // Top Header Banner
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("MediKiosk Healthcare Platform", 14, 14);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("PHYSICIAN CLINICAL INTAKE REPORT", 14, 21);
  doc.text(`Date: ${date}`, pageWidth - 14, 21, { align: "right" });

  let y = 36;

  // Patient Info & Session Overview Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, y, pageWidth - 28, 24, 3, 3, "FD");

  doc.setTextColor(...darkTextColor);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(`Patient: ${patientName}`, 18, y + 8);
  doc.text(`Chief Complaint: ${chiefComplaint || "General Assessment"}`, 18, y + 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...grayColor);
  doc.text("Status: COMPLETED (AI Verified)", pageWidth - 18, y + 8, { align: "right" });
  doc.text("Source: MediKiosk RAG Engine", pageWidth - 18, y + 16, { align: "right" });

  y += 30;

  // Physician Clinical Briefing Box
  doc.setFillColor(241, 245, 249);
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(14, y, pageWidth - 28, 22, 3, 3, "FD");

  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.text("ATTENDING PHYSICIAN CLINICAL BRIEFING & ACTION NOTES", 18, y + 6);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85);
  const briefingText = "This pre-consultation report is generated by the MediKiosk Clinical AI RAG Engine. It compiles self-reported progression and parameters. Please verify identified red flags during physical exam and validate diagnostic differentials prior to treatment planning.";
  const splitBriefing = doc.splitTextToSize(briefingText, pageWidth - 36);
  doc.text(splitBriefing, 18, y + 12);

  y += 28;

  // Red Flags Alert Section (if present)
  if (redFlags && redFlags.length > 0) {
    doc.setFillColor(254, 242, 242);
    doc.setDrawColor(254, 202, 202);
    doc.roundedRect(14, y, pageWidth - 28, 10 + redFlags.length * 6, 3, 3, "FD");

    doc.setTextColor(220, 38, 38);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.text("RED FLAGS IDENTIFIED", 18, y + 7);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(153, 27, 27);
    redFlags.forEach((flag, idx) => {
      doc.text(`* ${flag}`, 22, y + 13 + idx * 6);
    });

    y += 16 + redFlags.length * 6;
  }

  // Answered Parameters Table
  if (answeredFields && Object.keys(answeredFields).length > 0) {
    doc.setTextColor(...primaryColor);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Structured Clinical History & Parameters", 14, y);
    y += 6;

    doc.setFontSize(9);
    const entries = Object.entries(answeredFields);
    entries.forEach(([key, val]) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      const label = key.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase());
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...darkTextColor);
      doc.text(`${label}:`, 18, y);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(51, 65, 85);
      doc.text(String(val), 70, y);
      y += 5.5;
    });

    y += 6;
  }

  // Summary Text Section
  if (summaryText) {
    if (y > 240) {
      doc.addPage();
      y = 20;
    }
    doc.setTextColor(...primaryColor);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Physician Summary Notes", 14, y);
    y += 6;

    const cleanText = summaryText
      .replace(/###/g, "")
      .replace(/\*\*/g, "")
      .replace(/\*/g, "")
      .replace(/🩺|📋|🚨/g, "")
      .trim();

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...darkTextColor);

    const splitText = doc.splitTextToSize(cleanText, pageWidth - 28);
    splitText.forEach((line) => {
      if (y > 275) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, 14, y);
      y += 4.5;
    });
  }

  // Footer on all pages
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `MediKiosk AI Intake Report - Page ${i} of ${pageCount} - Confidential Medical Document`,
      pageWidth / 2,
      287,
      { align: "center" }
    );
  }

  const sanitizedPatient = patientName.replace(/[^a-zA-Z0-9]/g, "_");
  const sanitizedComplaint = (chiefComplaint || "General").replace(/[^a-zA-Z0-9]/g, "_");
  const timestamp = new Date().toISOString().slice(0, 10);
  const randomCode = Math.floor(1000 + Math.random() * 9000);

  const safeFilename = `MediKiosk_Assessment_${sanitizedPatient}_${sanitizedComplaint}_${timestamp}_Ref${randomCode}.pdf`;
  doc.save(safeFilename);
}
